kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: generic-watcher
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - "tekton.dev"
    resources:
      - taskruns
      - pipelineruns
