apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: generic-eventlistener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: generic-triggerbinding
      name: print-generic
      template:
        ref: "print-generic-template"
      interceptors:
        - cel:
            filter: header.match('Ce-Type', 'dev.knative.apiserver.resource.update')
        - cel:
            filter: body.metadata.generateName != ''
        - cel:
            filter: body.status.conditions[0].reason == "Succeeded"
        - cel:
            filter: body.spec.taskRef.name == "buildah"
    - bindings:
        - ref: code-change-triggerbinding
      name: code-change
      template:
        ref: "code-change-template"
      interceptors:
        - cel:
            filter: header.match('Ce-Type', 'dev.knative.apiserver.resource.update')
        - cel:
            filter: body.metadata.generateName != ''
        - cel:
            filter: body.status.conditions[0].reason == "Succeeded"
        - cel:
            filter: body.spec.taskRef.name == "make"
        - cel:
            filter: body.spec.params[0].value != 'run-integration-tests'
        - cel:
            filter: body.spec.params[0].value != 'test'
        - cel:
            filter: body.spec.params[1].value != 'run-integration-tests'
        - cel:
            filter: body.spec.params[1].value != 'test'
        - cel:
            filter: body.spec.params[2].value != 'run-integration-tests'
        - cel:
            filter: body.spec.params[2].value != 'test'
#body.spec.params[?(@.name=='docker-namespace')].value
    - bindings:
        - ref: generic-triggerbinding
      name: print-generic
      template:
        ref: "print-generic-template"
      interceptors:
        - cel:
            filter: header.match('Ce-Type', 'dev.knative.apiserver.resource.update')
        - cel:
            filter: body.status.conditions[0].reason == "Succeeded"
        - cel:
            filter: body.spec.taskRef.name == "buildah"
        - cel:
            filter: body.metadata.labels['triggers.tekton.dev/trigger'] == "code-change"
