{{- if .Values.worker.enabled }}
{{- if not (.Values.clusterScoped) }}
# Role batchtransfer-editor allows managing batchtransfers
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fybrik.fullname" . }}-batchtransfer-role
rules:
- apiGroups: ["motion.m4d.ibm.com"]
  resources: ["batchtransfers", "batchtransfers/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["motion.m4d.ibm.com"]
  resources: ["batchtransfers/status"]
  verbs: ["get", "update", "patch"]
{{- end }}
{{- end }}
