{{- if .Values.worker.enabled }}
{{- if not (.Values.clusterScoped) }}
# ClusterRole streamtransfer-editor allows managing streamtransfers
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fybrik.fullname" . }}-streamtransfer-role
rules:
- apiGroups: ["motion.fybrik.io"]
  resources: ["streamtransfers", "streamtransfers/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["motion.fybrik.io"]
  resources: ["streamtransfers/status"]
  verbs: ["get", "update", "patch"]
{{- end }}
{{- end }}
